# -*- coding: utf-8 -*-
"""prophet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/SanjeevKurJha/MachineLearning/blob/master/Time%20Series/prophet.ipynb
"""

pip install prophet

"""**Importing the library, here we are importing very important library called Prophet( Thank to Facbook for one of the best library)**"""

from fbprophet import Prophet
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

"""**Loading the flight dataset from seaborn**"""

df = sns.load_dataset("flights")

"""**Exploratory Data Analysis**"""

df.head()
df.tail()
df.shape
df.describe()
df.info()

data=df.loc[:,['passengers']]
data.head()

"""**One mandotary task we need to do in time series modle to conver data column in below format (19490131 --- 1949/01/31)**

**As we can see our dataset in montholy period**
"""

month = pd.date_range('19490131', periods = 144, freq = 'M')
month

"""**Our Prophet model have one assumption we need to alway take two column "ds","y"**"""

df['ds']=month
df.head()

df=df.rename(columns={"passengers":"y"})
df=df.sort_index(axis=1)
df.head()

"""**Data forcasting with 95 % confidence interval**"""

forcast_my=Prophet(interval_width=0.95)
forcast_my.fit(df)

forcast_periods=forcast_my.make_future_dataframe(periods=36,include_history=True,freq='M')
forcast_periods

"""**here yhat is the predicted value**"""

forcast=forcast_my.predict(forcast_periods)
forcast_One=forcast.loc[:,['ds','yhat']]
forcast_One.head()

forcast_my.plot(forcast,uncertainty=True)

forcast_my.plot_components(forcast)

df_final=pd.merge(forcast_One,df,on='ds',how='inner')
df_final.head()

import numpy as np
from sklearn import metrics
np.round(metrics.mean_absolute_error(df_final.yhat,df_final.y),0)

df.head()

df.y=np.log(df.y)
df.head()

forcast_my=Prophet(interval_width=0.95)
forcast_my.fit(df)
forcast_periods=forcast_my.make_future_dataframe(periods=36,include_history=True,freq='M')
forcast=forcast_my.predict(forcast_periods)
forcast_One=forcast.loc[:,['ds','yhat']]
forcast_One.head()
forcast_my.plot(forcast,uncertainty=True)

forcast_my.plot_components(forcast)

#forcast_my.plot_components(forcast)
df_final=pd.merge(forcast_One,df,on='ds',how='inner')
df_final.head()

df_final.yhat=np.e**(df_final.yhat)
df_final.y=np.e**(df_final.y)
df_final.head()

np.round(metrics.mean_absolute_error(df_final.yhat,df_final.y),0)

df_final.info()
df_final.describe()
df_final.head()
df_final.tail()

"""**Generate For cast Value for next 24 month**"""

forcast_two=forcast.loc[144:,['ds','yhat','yhat_lower','yhat_upper']]
forcast_two.head()
forcast_two.yhat=np.e**(forcast_two.yhat)
forcast_two.yhat_lower=np.e**(forcast_two.yhat_lower)
forcast_two.yhat_upper=np.e**(forcast_two.yhat_upper)
np.round(forcast_two)

sns.tsplot(forcast_two.yhat)
plt.show()